---
abstract: 'write Excel spreadsheets from Mojolicious'
author:
  - 'Zak B. Elep <zakame@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.3.0, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-WriteExcel
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Mojolicious::Plugin::WriteExcel:
    file: lib/Mojolicious/Plugin/WriteExcel.pm
    version: '2.03'
requires:
  Mojolicious: '0.999930'
  Spreadsheet::WriteExcel::Simple: '0'
resources:
  bugtracker: https://github.com/zakame/mojox-renderer-writeexcel/issues
  homepage: https://github.com/zakame/mojox-renderer-writeexcel
  repository: git://github.com/zakame/mojox-renderer-writeexcel.git
version: '2.03'
x_contributors:
  - 'Zak B. Elep <zakame@zakame.net>'
